version: '3'
services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb-flexable
    restart: always
    volumes:
      - ./data/influxdb:/var/lib/influxdb
#      - ./conf/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
  # query influx using 
  # docker-compose exec influxdb influx
    environment:
      - INFLUXDB_DB=flexABLE
#      - INFLUXDB_USER=telegraf
#      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
      - INFLUXDB_META_DIR=/var/lib/influxdb/meta2
  
  grafana:
    image: grafana/grafana-oss
    container_name: flexable-grafana
    user: "104"
    depends_on:
      - influxdb
    ports:
      - 3001:3000
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboard-definitions:/etc/grafana/provisioning/dashboard-definitions
