#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Sep 30, 2021 03:30:18 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global tch_importStorages
    tch_importStorages = tk.IntVar()
    global tch_importCRM
    tch_importCRM = tk.IntVar()
    global tch_importDHM
    tch_importDHM = tk.IntVar()
    global tch_importCBT
    tch_importCBT = tk.IntVar()
    global tch_checkAvailability
    tch_checkAvailability = tk.IntVar()
    global tch_meritOrder
    tch_meritOrder = tk.IntVar()
    
def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def start():
    print('supportVariables.start')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import unknown
    unknown.vp_start_gui()




