{
 "title": "FlexABLE",
 "time": { "from": "2015-12-31T23:00:00.000Z", "to": "2016-12-31T23:00:00.000Z" },
 "panels": [
  {
   "title": "Merit Order Price",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "€/MWh" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "simulationID" ], "type": "tag" },
      { "params": [ "user" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PFC",
     "select": [
      [
       { "params": [ "Merit Order Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "MeritOrder" ], "type": "alias" }
      ],
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Price" ], "type": "alias" }
      ],
      [
       { "params": [ "IED_Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "IED Price" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "alias": "$col - $tag_Technology",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Technology" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Power",
     "select": [
      [
       { "params": [ "Power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Power_Flex" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Merit Order Price",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "€/MWh" } },
   "targets": [
    {
     "alias": "$col - $tag_Technology",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Technology" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Capacities",
     "select": [
      [
       { "params": [ "Flex_Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "FlexPrice" ], "type": "alias" }
      ],
      [
       { "params": [ "MR_Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "MR_Price" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Production Capacities",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "alias": "$col - $tag_Technology",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Technology" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Capacities",
     "select": [
      [
       { "params": [ "Power_Flex" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Power_Flex" ], "type": "alias" }
      ],
      [
       { "params": [ "Power_MR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Power_MR" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}